name = "hello-python-worker-test-fds"
main = "entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-03-18"

kv_namespaces = [
    { binding = "FOO", id = "16b58881cd214381b9df2060b5fe3ade" }
]